global using System;
global using Shouldly;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using TestCommon.TestUtil;
global using NS = NSubstitute;
global using NSubstitute;
global using MS = Sqleze.Mock.MockSqlClient;
global using MSS = Sqleze.Mock.MockSqlClientServer;
global using DryIoc;
global using TestCommon.DependencyInjection;